#!/bin/bash

#*****************************************************************************
#
# Build environment - Ubuntu 64-bit Server 24.04.2
#
# sudo apt update
# sudo apt install build-essential clang flex bison g++ gawk \
# gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
# python3-setuptools rsync swig unzip zlib1g-dev file wget
#
#*****************************************************************************

echo "clean up previous attempt"
rm -rf openwrt
rm -rf mtk-openwrt-feeds

echo "clone openwrt branch"
git clone --branch openwrt-24.10 https://git.openwrt.org/openwrt/openwrt.git openwrt || true
cd openwrt; git checkout 3a481ae21bdc504f7f0325151ee0cb4f25dfd2cd; cd -;		#toolchain: mold: add PKG_NAME to Makefile

echo "clone mtk branch"
git clone https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds || true
cd mtk-openwrt-feeds; git checkout 72fa6744f53dfccfbb2884de9e8aa8a3bf444e74; cd -;	#HEAD @ 72fa6744 [kernel-6.6][mt7987][switch][Add AN8855 gsw driver]

echo '### wireless-regdb modification - this remove all regdb wireless countries restrictions ###'
rm -rf openwrt/package/firmware/wireless-regdb/patches/*.*
rm -rf mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches/*.*
\cp -r patch/500-tx_power.patch mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/files/package/firmware/wireless-regdb/patches
\cp -r patch/regdb.Makefile openwrt/package/firmware/wireless-regdb/Makefile

echo '### jumbo frames support ###'
\cp -r patch/750-mtk-eth-add-jumbo-frame-support-mt7998.patch openwrt/target/linux/mediatek/patches-6.6

echo '### SFP-GE-T-ignore-TX_FAULT ###'
\cp -r patch/790-SFP-GE-T-ignore-TX_FAULT.patch openwrt/target/linux/mediatek/patches-6.6

echo '### Thermal patch ###'
\cp -r patch/mt7988a-bananapi-bpi-r4.dtsi openwrt/target/linux/mediatek/patches-6.6
\cp -r patch/mt7988a.dtsi openwrt/target/linux/mediatek/patches-6.6

echo '### required & thermal zone ###'
\cp -r patch/1007-wozi-arch-arm64-dts-mt7988a-add-thermal-zone.patch mtk-openwrt-feeds/24.10/patches-base/

sed -i 's/CONFIG_PACKAGE_perf=y/# CONFIG_PACKAGE_perf is not set/' mtk-openwrt-feeds/autobuild/unified/filogic/mac80211/24.10/defconfig
sed -i 's/CONFIG_PACKAGE_perf=y/# CONFIG_PACKAGE_perf is not set/' mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7988_wifi7_mac80211_mlo/.config
sed -i 's/CONFIG_PACKAGE_perf=y/# CONFIG_PACKAGE_perf is not set/' mtk-openwrt-feeds/autobuild/autobuild_5.4_mac80211_release/mt7986_mac80211/.config

echo '### dive in ###'
cd openwrt

echo '### adapt feed rev ###'
cat <<-EOF > feeds.conf.default
src-git-full packages https://git.openwrt.org/feed/packages.git^e4be6db
src-git-full luci https://git.openwrt.org/project/luci.git^9453d7d
src-git-full routing https://git.openwrt.org/feed/routing.git^f2ee837
EOF

bash ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh filogic-mac80211-mt7988_rfb-mt7996 log_file=make

exit 0


#umask 022
#git clone --depth 1 --branch master --single-branch --no-tags --recurse-submodules https://github.com/fantastic-packages/packages package/fantastic_packages


